# Stati Categorie
INSERIMENTO_NOME_CATEGORIA, SCELTA_DOPO_CATEGORIA = range(2)

# Stati Prodotti
SCELTA_CATEGORIA_PRODOTTO, NOME_PRODOTTO, QUANTITA_PRODOTTO, SOGLIA_PRODOTTO, FINE_PRODOTTO, MODIFICA_PRODOTTO = range(10, 16)